USE QLDT
GO

-- đếm số lượng giáo viên không phải quản lý
SELECT COUNT(*) AS SOLUONG
FROM GIAOVIEN
WHERE GIAOVIEN.GVQLCM IS NOT NULL

-- đếm số lượng giáo viên quản lý gíao viên khác và thuộc bộ môn httt
SELECT COUNT(*) AS SOLUONG
FROM GIAOVIEN
WHERE GIAOVIEN.MABM = 'HTTT' AND GIAOVIEN.GVQLCM IS NULL
-- OR
SELECT COUNT(GIAOVIEN.GVQLCM)
FROM GIAOVIEN
WHERE GIAOVIEN.MABM = 'HTTT'

-- đếm số lượng giáo viên quản lý
SELECT COUNT(GIAOVIEN.GVQLCM)
FROM GIAOVIEN

-- tính lương trung bình của các giáo viên bộ môn hệ thống thông tin
SELECT AVG(GIAOVIEN.LUONG) AS LUONG_TB
FROM GIAOVIEN, BOMON
WHERE GIAOVIEN.MABM = BOMON.MABM
    AND BOMON.TENBM = N'Hệ thống thông tin'

-- với mỗi giáo viên, cho biết mã giáo viên và số lượng công việc mà giáo viên đó tham gia
SELECT GIAOVIEN.HOTEN, GIAOVIEN.MAGV, COUNT(*)
FROM GIAOVIEN, THAMGIADT
WHERE GIAOVIEN.MAGV = THAMGIADT.MAGV
GROUP BY GIAOVIEN.MAGV, GIAOVIEN.HOTEN

SELECT MAGV, COUNT(*) AS SLCV FROM THAMGIADT
GROUP BY MAGV

-- số lượng đề tài mỗi giáo viên tham gia
SELECT GIAOVIEN.MAGV, GIAOVIEN.HOTEN, COUNT(DISTINCT THAMGIADT.MADT) AS SLDT
FROM GIAOVIEN, THAMGIADT
WHERE GIAOVIEN.MAGV = THAMGIADT.MAGV
GROUP BY GIAOVIEN.MAGV, GIAOVIEN.HOTEN

-- cho biết số lượng giáo viên tham gia mỗi bộ môn
SELECT BOMON.MABM, BOMON.TENBM, COUNT(*) AS SOLUONG
FROM BOMON, GIAOVIEN
WHERE BOMON.MABM = GIAOVIEN.MABM
GROUP BY BOMON.MABM, BOMON.TENBM

SELECT MABM, COUNT(*)
FROM GIAOVIEN
GROUP BY MABM

-- với mỗi bộ môn, cho biết số lượng đề tài mà giáo viên của bộ môn đó chủ trì
SELECT BOMON.MABM, BOMON.TENBM, COUNT(*)
FROM BOMON, GIAOVIEN, DETAI
WHERE GIAOVIEN.MABM = BOMON.MABM AND DETAI.GVCNDT = GIAOVIEN.MAGV
GROUP BY BOMON.MABM, BOMON.TENBM

SELECT GV.MABM, COUNT(*) FROM DETAI DT, GIAOVIEN GV WHERE DT.GVCNDT = GV.MAGV GROUP BY GV.MABM

-- cho biết tên bộ môn và số lượng giáo viên của bộ môn đó
SELECT BOMON.TENBM, COUNT(*)
FROM BOMON, GIAOVIEN
WHERE GIAOVIEN.MABM = BOMON.MABM
GROUP BY BOMON.TENBM

-- cho biết các bộ môn có từ 2 giáo viên trở lên 
SELECT MABM, COUNT(*)
FROM GIAOVIEN 
GROUP BY MABM HAVING COUNT(*) >= 2

-- tên giáo viên + số lượng đề tài mà thanh niên tham gia (nhưng phải lớn hơn 3 đề tài mới join)
SELECT GIAOVIEN.HOTEN, COUNT(DISTINCT THAMGIADT.MADT)
FROM GIAOVIEN, THAMGIADT
WHERE GIAOVIEN.MAGV = THAMGIADT.MAGV
GROUP BY GIAOVIEN.MAGV, GIAOVIEN.HOTEN
HAVING COUNT(DISTINCT THAMGIADT.MADT) >= 3

SELECT GV.HOTEN, COUNT( DISTINCT TG.MADT) AS SOLUONGDT FROM GIAOVIEN GV, THAMGIADT TG
WHERE GV.MAGV = TG.MAGV
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT( DISTINCT TG.MADT) >= 3










