USE QLDT
GO

-- Q46.Cho biết giáo viên có lương lớn hơn lương của giáo viên “Nguyễn Hoài An”
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV
WHERE GV.LUONG > (
  SELECT GV1.LUONG
  FROM GIAOVIEN GV1
  WHERE GV1.HOTEN = N'Nguyễn Hoài An'
)

-- Q47.Tìm nhữngtrưởng bộmôn tham gia tối thiểu 1 đềtài
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV, BOMON BM
WHERE GV.MAGV = BM.TRUONGBM
  AND GV.MAGV = ANY (
 SELECT T.MAGV
 FROM THAMGIADT T
  )

-- Q48.Tìm giáo viên trùng tên và cùng giới tính với giáo viên khác trong cùng bộmôn
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV
WHERE EXISTS (
  SELECT *
  FROM GIAOVIEN GV1
  WHERE GV1.HOTEN = GV.HOTEN AND GV1.PHAI = GV.PHAI AND GV1.MAGV <> GV.MAGV
)

-- Q49.Tìm những giáo viên có lương lớn hơn lương của ít nhất một giáo viên bộmôn “Công nghệphần mềm”
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV
WHERE GV.LUONG > ANY (
  SELECT GV1.LUONG 
  FROM GIAOVIEN GV1, BOMON BM
  WHERE GV1.MABM = BM.MABM AND BM.TENBM = N'Công nghệ phần mềm'
)

-- Q50.Tìm những giáo viên có lương lớn hơn lương của tất cảgiáo viên thuộc bộmôn “Hệ thống thông tin"
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV
WHERE GV.LUONG > ALL (
  SELECT GV1.LUONG
  FROM GIAOVIEN GV1, BOMON BM
  WHERE GV1.MABM = BM.MABM AND BM.TENBM = N'Hệ thống thông tin'
)

-- Q51.Cho biết tên khoa có đông giáo viên nhất
SELECT K.TENKHOA, COUNT(*)
FROM KHOA K, GIAOVIEN GV, BOMON BM
WHERE GV.MABM = BM.MABM AND BM.MAKHOA = K.MAKHOA
GROUP BY K.MAKHOA, K.TENKHOA
HAVING COUNT(*) >= ALL (
  SELECT COUNT(*)
  FROM KHOA K, GIAOVIEN GV, BOMON BM
  WHERE GV.MABM = BM.MABM AND BM.MAKHOA = K.MAKHOA
  GROUP BY K.MAKHOA, K.TENKHOA
)

-- Q52.Cho biết họtên giáo viên chủnhiệm nhiều đềtài nhất
SELECT GV.HOTEN, COUNT(*)
FROM DETAI D, GIAOVIEN GV
WHERE D.GVCNDT = GV.MAGV
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(*) >= ALL (
  SELECT COUNT(*)
  FROM DETAI D, GIAOVIEN GV
  WHERE D.GVCNDT = GV.MAGV
  GROUP BY GV.MAGV, GV.HOTEN
)

-- Q53.Cho biết mã bộmôn có nhiều giáo viên nhất
SELECT GV.MABM, COUNT(*)
FROM GIAOVIEN GV
GROUP BY GV.MABM
HAVING COUNT(*) >= ALL (
  SELECT COUNT(*)
  FROM GIAOVIEN GV
  GROUP BY GV.MABM
)

-- Q54.Cho biết tên giáo viên và tên bộmôn của giáo viên tham gia nhiều đềtài nhất
SELECT GV.HOTEN, BM.TENBM, COUNT(DISTINCT T.MADT)
FROM GIAOVIEN GV, BOMON BM, THAMGIADT T
WHERE GV.MABM = BM.MABM AND T.MAGV = GV.MAGV
GROUP BY GV.HOTEN, BM.TENBM
HAVING COUNT(DISTINCT T.MADT) >= ALL (
  SELECT COUNT(DISTINCT T.MADT)
  FROM GIAOVIEN GV, BOMON BM, THAMGIADT T
  WHERE GV.MABM = BM.MABM AND T.MAGV = GV.MAGV
  GROUP BY GV.HOTEN, BM.TENBM
)

-- SELECT GV.HOTEN, BM.MABM, COUNT(TGDT.MADT) AS SOLUONG
-- FROM GIAOVIEN GV,THAMGIADT TGDT,BOMON BM
-- WHERE GV.MAGV=TGDT.MAGV AND BM.MABM=GV.MABM
-- GROUP BY GV.HOTEN, BM.MABM
-- HAVING COUNT(TGDT.MADT) = (
-- 				SELECT TOP (1) COUNT(TGDT.MADT) AS SOLUONG
-- 				FROM GIAOVIEN GV,THAMGIADT TGDT,BOMON BM
-- 				WHERE GV.MAGV=TGDT.MAGV AND BM.MABM=GV.MABM
-- 				GROUP BY GV.HOTEN, BM.MABM
-- 				ORDER BY SOLUONG DESC
-- 				)

-- Q55.Cho biết tên giáo viên tham gia nhiều đềtài nhất của bộmôn HTTT
SELECT DISTINCT GV.MAGV, GV.HOTEN, COUNT(DISTINCT T.MADT)
FROM GIAOVIEN GV, THAMGIADT T
WHERE GV.MABM = 'HTTT' AND GV.MAGV = T.MAGV
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT T.MADT) >= ALL (
  SELECT COUNT(DISTINCT T1.MADT)
  FROM THAMGIADT T1, GIAOVIEN GV1
  WHERE T1.MAGV = GV1.MAGV
  GROUP BY GV1.MAGV
)

-- SELECT HTTT.HOTEN,COUNT(TGDT.MAGV)
-- FROM GIAOVIEN HTTT, THAMGIADT TGDT
-- WHERE HTTT.MAGV=TGDT.MAGV AND HTTT.MABM='HTTT'
-- GROUP BY HTTT.HOTEN
-- HAVING COUNT(TGDT.MAGV) = (
-- 				SELECT TOP (1)COUNT(TGDT.MAGV)
-- 				FROM GIAOVIEN HTTT, THAMGIADT TGDT
-- 				WHERE HTTT.MAGV=TGDT.MAGV AND HTTT.MABM='HTTT'
-- 				GROUP BY HTTT.HOTEN
-- 				ORDER BY COUNT(TGDT.MAGV) DESC
-- 				)

