USE QLDT
GO

SELECT BM.TENBM, COUNT(*)
FROM BOMON BM, GIAOVIEN GV
WHERE BM.MABM = GV.MABM
GROUP BY BM.TENBM

SELECT BM.TENBM, ( 
        SELECT COUNT(*)
        FROM GIAOVIEN GV
        WHERE GV.MABM = BM.MABM
    )
FROM BOMON BM

SELECT * FROM BOMON

SELECT BM.TENBM, SUM(GV.LUONG)
FROM BOMON BM, GIAOVIEN GV
WHERE BM.MABM = GV.MABM
GROUP BY BM.TENBM


SELECT GV.MABM, GV.LUONG
FROM GIAOVIEN GV
WHERE GV.LUONG = (
    SELECT MAX(GV1.LUONG)
    FROM GIAOVIEN GV1
    -- WHERE GV1.MABM = GV.MABM
)
-- GROUP BY GV.MABM, GV.LUONG
